.TH FPAC.HELLO 5 "23 September 2011" Linux "FPAC Operator's Manual"
.SH NAME 
fpac.hello \- FPAC node greeting text
.SH DESCRIPTION
.LP
.B fpac.hello
contains the Greeting text sent to each user as they connect to the node.
.SH EXAMPLE
You are connected to the Citrus County FPAC Node
    *  Located in Cedar Cove, Fla  *

.SH FILES
.IP "/etc/ax25/fpac.hello"
.SH AUTHOR
Bernard Pidoux F6BVP <bernard.f6bvp@gmail.com>
.SH SEE ALSO
fpac.dnic(5) fpac.info(5) fpac.conf(5) fpac.nodes(5) fpac.routes(5)
