.TH FPAC.INFO 5 "23 September 2011" Linux "FPAC Operator's Manual"
.SH NAME 
fpac.info \- FPAC node information text."
.SH DESCRIPTION
.LP
.B fpac.info
contains the information text sent to the user in response to the FPAC command Info.
.SH EXAMPLE
This FPAC node is a part of the FADCA Layered Network.
FPAC is basically a ROSE switch which can interface with NetRom and or
Flexnet Networks. The Packet server is built on a Linux (Ubuntu) OS.

Comments or questions should be directed to Charley Schuman
 E-MAIL
	k4gbb1@gmail.com
 PACKET
	k4gbb@k4gbb.#citfl.fl.usa.noam
.SH FILES
.IP "/etc/ax25/fpac.info"
.SH AUTHOR
Bernard Pidoux F6BVP <bernard.f6bvp@gmail.com>
.SH SEE ALSO
fpac.hello(5) fpac.dnic(5) fpac.conf(5) fpac.nodes(5) fpac.routes(5)
