.TH FPAC.DNIC 5 "23 September 2011" Linux "FPAC Operator's Manual"
.SH NAME 
fpac.dnic \- FPAC DNIC text
.SH DESCRIPTION
.LP
.B fpac.dnic
contains a table for displaying text in place of the DNIC. This allows the operator to substitute text in place of a the numeric code. The user friendly country names in the left column are substituted for the DNIC in the right hand column.
.SH EXAMPLE
 FRA 2080
 ESP 2120
 ITL 2220
 CAN 3020
 USA 3100
 CUR 3620
 ARU 3630
 AUS 5050
 NIC 7100
 COS 7120
.SH FILES
.IP "/etc/ax25/fpac.dnic"
.SH AUTHOR
Bernard Pidoux F6BVP <bernard.f6bvp@gmail.com>
.SH SEE ALSO
fpac.hello(5) fpac.info(5) fpac.conf(5) fpac.nodes(5) fpac.routes(5)
