.TH MYFPAC.SH 1 "2 June 2026" Linux "FPAC Operator's Manual"
.SH NAME
myfpac.sh \- Bash shell script to control FPAC application daemons.
.SH SYNOPSIS
.B myfpac.sh start|stop|restart|status
.SH DESCRIPTION
.LP
.B myfpac.sh
Starts/stops the application daemons of an FPAC node. The AX.25 link layer
(kissattach, ax25ipd, netromd, ...) is managed separately by ax25up/ax25stop
and is deliberately left running.
.SH ACTIONS
.TP 10
.BI "\ Start -"
Start FPAC - Start up elements of the FPAC node
.TP 
.BI "\ Stop -"
Stop - FPAC - Shutdown Node
.TP 11
.BI "\ Restart -"
Restart - Stop then Start FPAC.
.TP 10
.BI "\ Status -"
Display the Status of FPAC elements.
.SH AUTHOR
Bernard Pidoux F6BVP <bernard.f6bvp@gmail.com>
.SH See Also
 fpad(1) fpacwpd(1) fpacstat(1) fpacroute(1) fpacwdog(1) flexd(1) mailbbs(1)
