.TH WPSERV 1 "23 September 2011" Linux "FPAC Operator's Manual"
.SH NAME 
wpserv /- FPAC White Page Database server.
.SH SYNOPSIS
.B wpserv [-n] [-l num] [-c] [-r] [-a] [mask*] 
.SH DESCRIPTION
.LP
.B wpserve
returns a listing of records that match the search options.
.SH OPTIONS
.TP 13
.BI \-n 
List nodes only
.TP 13
.BI \-l " <num>
List num records. The default is 10.
.TP 13
.BI \-c
Sort by call. (default)
.TP 13
.BI \-r
Display in reverse order.
.TP 13
.BI \-a
Sort by Address.
.TP 13
.BI \ mask*
List records which match the mask.
.SH AUTHOR
Bernard Pidoux F6BVP <bernard.f6bvp@gmail.com>
