.TH FPACCFG 1 "23 September 2011" Linux "FPAC Operator's Manual"
.SH NAME 
fpaccfg \- Displays FPAC node configuration.
.SH SYNOPSIS
.B fpaccfg
.SH DESCRIPTION
.LP
.B fpaccfg
reads the FPAC configuration files and displays the information on the local console.
.SH AUTHOR
Bernard Pidoux F6BVP <bernard.f6bvp@gmail.com>
