.TH FPACSHELL 1 "23 September 2011" Linux "FPAC Operator's Manual"
.SH NAME 
fpacshell \- command line shell for FPAC node.
.SH SYNOPSIS
.B fpacshell
.SH DESCRIPTION
.LP
.B fpacshell
runs a shell with MD5 protection from the FPAC node. Fpacshell is executed in response to the FPAC SYSop command.
.SH AUTHOR
Bernard Pidoux F6BVP <bernard.f6bvp@gmail.com>
