.TH REMOTE.1 "23 September 2011" Linux "FPAC Operator's Manual"
.SH NAME
remote \- remote control via a parallel port
.SH SYNOPSIS
.B remote [-c bit] [-s bit] [-h] 
.SH DESCRIPTION 
.LP
.B remote
allows the user to set or reset the output bits of the parallel port.
.SH OPTIONS
.TP 20 
.BI \-c " <bit> 
Clear bit (0-7).
.TP 20
.BI \-s " <bit>
Set bit (0-7).
.TP 20
.BI \-h 
Show help. 
.SH AUTHOR
Bernard Pidoux F6BVP <bernard.f6bvp@gmail.com>
